const fs = require("fs");
const path = require("path");

const envPath = path.join(__dirname, "../.env");
const outputPath = path.join(__dirname, "../extension/env.js");

let envContent = "";
try {
  envContent = fs.readFileSync(envPath, "utf8");
} catch (e) {
  console.warn("Paendeo build: .env file not found in root. Generating empty env.js");
}

const keys = {
  openai: "",
  anthropic: "",
  gemini: ""
};

envContent.split("\n").forEach((line) => {
  const cleanLine = line.trim();
  if (!cleanLine || cleanLine.startsWith("#")) return;
  const eqIdx = cleanLine.indexOf("=");
  if (eqIdx > 0) {
    const key = cleanLine.substring(0, eqIdx).trim();
    const val = cleanLine.substring(eqIdx + 1).trim();
    if (key === "OPENAI_API_KEY") keys.openai = val;
    if (key === "ANTHROPIC_API_KEY") keys.anthropic = val;
    if (key === "GEMINI_API_KEY") keys.gemini = val;
  }
});

const outputJs = `// Automatically generated by scripts/inject-env.js. Do not edit directly.
self.ENV_KEYS = ${JSON.stringify(keys, null, 2)};
`;

fs.writeFileSync(outputPath, outputJs, "utf8");
console.log("Paendeo build: Successfully generated extension/env.js from root .env");
